### ISSUE TITLE
Create models

### ISSUE THREAD

**Issue by david2242** [david2242/student-competition#3]
Student:
- name: string -> Kálmán Ferencz
- class: -> 2022. b.

Competition:
- name: string
- location: string
- subject: string[]
- teacher: string[]
- year: string -> 2004-2005
- date: Date (might be unneccessary)
- level: 'local' | 'state' | 'regional' | 'national' | 'international'
- round: 'school' | 'regional' | 'state' | 'national'
- form: 'written' | 'oral' | 'sport' | 'submission' []
- "result":{
	- position:null,
	- special_prize: boolean
	  compliment: boolean
	- next_round: boolean }
- other: string

**Comment by norbfr** [comment]
Lenne pár kérdésem:
1. A location mező milyen adattal dolgozna? Látom, hogy a típus az string lenne, de miért van ott mögötte a () jelzés?
2. Az other mező az megjegyzés funkcionalitást töltene be esetleg? Ha igen akkor olyan nevet adnék neki, ha az megfelelő.
3. A subject, illetve teacher mezők ha jól gondolom a [ ] jelölés alapján tömbként fognak funkcionálni igaz?
4. A form mező esetében többet is meg lehet adni a lehetséges értékekből, így ezáltal tömbként létezne ez a mező? Emiatt van ott mögötte a tömb [ ] jelölés?

**Comment by david2242** [comment]
1. Yes, the "()" was not intended. It should store some kind of city i think, like "Budapest", or "Debrecen" etc.
2. Yes the other field is for any other comments related to the competition, but here is no field for it specified. What suggestion do you have with this naming?
3. The subject can be an array because the competition can have multiple subject such as ["mathematics", "physics"]. It would be nice to use enums but at the same time it should handle unspecified subjects, like new ones emerging in schools, like "visual culture" :D. 
4. Yeah the form should be an array as well because the competition can have multiple forms like ["oral", "written"].

**Comment by norbfr** [comment]
Thanks for the answer.

I suggest a name for the "other" field like a "note" or "comment". Which one do you think is appropriate? However if you think we should stick with the original name, that's OK for me.
